services:
    mysql:
      image: mysql:8.4
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        #Ниже - так подсказывает делать ИИ, но как будто слишком автоматизировано
        #volumes:
          #- ./mysql/dump-hibernate-final.sql:/docker-entrypoint-initdb.d/dump-hibernate-final.sql
      ports:
        - "3307:3306"
      healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_PASSWORD}" ]
        interval: 5s
        timeout: 5s
        retries: 10

#Вспомогательный инициализатор для контейнера mysql по healthcheck'у оного
    mysql-init:
      image: mysql:8.4

      depends_on:
        mysql:
          condition: service_healthy

      volumes:
        - ./mysql/dump-hibernate-final.sql:/init1.sql

      command: >
        sh -c
        "mysql -h mysql -uroot -p${MYSQL_PASSWORD} < /init1.sql"

    redis:
      image: redis:8
      ports:
        - "6380:6379"

    app:
      build: .
      depends_on:
        mysql-init:
          condition: service_completed_successfully
      environment:
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_URL: ${MYSQL_URL}